changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
    - title: 🎉 New Features
      labels:
        - is:feature
    - title: 🐞 Bug Fixes
      labels:
        - bug-fix
    - title: 🚀 Performance Improvements
      labels:
        - performance
    - title: 📄 Website and API Documentation
      labels:
        - docs
    - title: 💪 Other Changes
      labels:
        - "*"